#!bin/sh

#Give permission for init.d scrips for Oya
chmod +x /etc/init.d/oya

chmod +x /usr/bin/device_id

chmod +x /etc/init.d/recording
chmod +x /usr/bin/recording

chmod +x /usr/bin/state

chmod +x /usr/bin/uploading
chmod +x /etc/init.d/uploading

chmod +x /usr/bin/internet_status
chmod +x /etc/init.d/internet_status

chmod +x /etc/init.d/mqtt
chmod +x /usr/bin/mqtt

chmod +x /usr/bin/uart

chmod +x /usr/bin/flask_server
chmod +x /etc/init.d/flask_server

exit 0
