#!/bin/sh

uci set system.@system[-1].hostname="Oya"
uci set wireless.radio0.disabled=0
uci set network.lan.ipaddr=192.168.100.1

SSID=`fw_printenv -n wifi_ssid`
KEY=`fw_printenv -n wifi_key`
SEQ=`fw_printenv -n wifi_seq`
[ -n "${SSID}" ] || { \
	MAC=$(dd bs=1 skip=7 count=3 if=/dev/mtd2 2>/dev/null | hexdump -v -n 3 -e '3/1 "%02X"')
	SSID=Oya_${MAC}
}
[ -n "${SEQ}" ] || \
	SEQ=1
uci set wireless.ap.ssid="$SSID"
uci set wireless.ap.seq="$SEQ"

uci set wireless.ap.encryption='psk2'
uci set wireless.ap.key='oyalabs01'

uci commit wireless
uci commit

wifi_mode ap
exit 0
