#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
  python /Oya/flask_server/flask_server.py
}

stop() {
  pid=`flask_server pid get`
  kill -9 ${pid}
  flask_server pid remove
}

boot() {
	/etc/init.d/flask_server enable
}
