#!/bin/sh /etc/rc.common

#Flask server that helps user on-board
#Must start on boot
#Stop function gets pid and kills the process

START=97
STOP=99

start() {
  python /Oya/flask_server/flask_server.py
}

stop() {
  pid=`flask_server pid get`
  kill -9 ${pid}
  flask_server pid remove
}

boot() {
	/etc/init.d/flask_server enable
  /etc/init.d/flask_server start
}
