#!/bin/sh /etc/rc.common

#Runs a while loop to check internet status, if changed, it changes the inetrnet_status connected state and restarts the related processes: mqtt, uploading, islinked

START=99
STOP=99

start() {
  sh /Oya/internet_status.sh
}

stop() {
  internetStatusPid=`internet_status pid get`
  kill -9 ${internetStatusPid}
  internet_status pid remove
}

boot() {
	/etc/init.d/internet_status enable
}
