#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
  sh /Oya/internet_status.sh
}

stop() {
  internetStatusPid=`internet_status pid get`
  kill -9 ${internetStatusPid}
  internet_status pid remove
}

boot() {
	/etc/init.d/internet_status enable
}
