#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
  python /Oya/mqtt/mqtt_pubsub.py -e acovoelt8chys.iot.ap-southeast-1.amazonaws.com -r /Oya/mqtt/VeriSign-Class3-Public-Primary-Certification-Authority-G5.pem -c /Oya/mqtt/c50c61ff77-certificate.pem.crt -k /Oya/mqtt/c50c61ff77-private.pem.key -m publish -id `device_id get`
}

stop() {
  mqttPid=`mqtt pid get`
  kill -9 ${mqttPid}
  mqtt pid remove
}

boot() {
	/etc/init.d/mqtt enable
}
