#!/bin/sh /etc/rc.common

START=99
STOP=99

#MQTT process starts only when the device is connected to the interent
#stop function gets the PID, kills the process and removes the PID file.

start() {
  internet_status=`internet_status connected get`
  if [ ${internet_status} == "1" ]; then
    python /Oya/mqtt/mqtt_pubsub.py -e acovoelt8chys.iot.ap-southeast-1.amazonaws.com -r /Oya/mqtt/VeriSign-Class3-Public-Primary-Certification-Authority-G5.pem -c /Oya/mqtt/c50c61ff77-certificate.pem.crt -k /Oya/mqtt/c50c61ff77-private.pem.key -m publish -id `device_id get`
  fi
}

stop() {
  mqttPid=`mqtt pid get`
  kill -9 ${mqttPid}
  mqtt pid remove
}

boot() {
	/etc/init.d/mqtt enable
  #/etc/init.d/mqtt start
}
