#!/bin/sh /etc/rc.common

START=5

start()
{
	sh /Oya/main.sh
	uci set wireless.ap.ssid="Oya_DeviceID"
	uci set wireless.ap.key="Oyalabs"
	uci commit
	wifi
	wifi_mode ap
}
boot() {
  sh /Oya/main.sh
}
