#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
	sh /Oya/main.sh
}
boot() {
	/etc/init.d/oya enable
	#create all necessary directories
	mkdir /Media/SD-P1/recAudio
	mkdir /Media/SD-P1/uploadAudio
}
