#!/bin/sh /etc/rc.common

START=99
STOP=99

#To create base files and directories

start() {

}

boot() {
	/etc/init.d/oya enable
	#create all necessary directories
	mkdir /Media/SD-P1/recAudio
	mkdir /Media/SD-P1/uploadAudio
}
