#!/bin/sh /etc/rc.common

START=99
STOP=99


# Recording function starts only when the device isLinked to a user on the backend and it is not set to mute (is linked is not implemented and is defaulted to true on this version of the firmware)
# Stop fuction kills the recording process, also `arecord` process, in case `arecord` is still functioning and removes the PID files

start() {
  islinked=`state islinked get`
  mute=`state mute get`
  echo "islinked ${islinked}"
  echo "mute ${mute}"
  if [ ${islinked} == "1" ]; then
    if [ ${mute} == "0" ]; then
      if [ ! -f /Oya/pid/recording ]; then
        sh /Oya/recording.sh
        state recording set 1
      fi
    fi
  fi
}

stop() {
  recPid=`recording pid get`
  arecPid=`recording apid get`
  kill -9 ${recPid}
  kill -9 ${arecPid}
  recording pid remove
  recording apid remove
  state recording set 0
}

boot() {
	/etc/init.d/recording enable
}
