#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
  islinked=`state islinked get`
  mute=`state mute get`
  echo "islinked ${islinked}"
  echo "mute ${mute}"
  if [ ${islinked} == "1" ]; then
    if [ ${mute} == "0" ]; then
      if [ ! -f /Oya/pid/recording ]; then
        sh /Oya/recording.sh
      fi
    fi
  fi
}

stop() {
  recPid=`recording pid get`
  arecPid=`recording apid get`
  kill -9 ${recPid}
  kill -9 ${arecPid}
  recording pid remove
  recording apid remove
}

boot() {
	/etc/init.d/recording enable
}
