#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
  python /Oya/uart/uart_process.py
}

stop() {
  uartpid=`uart pid get`
  kill -9 ${uartpid}
  uart pid remove
}

boot() {
	/etc/init.d/uart enable
}
