#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
  sh /Oya/uart/uart_recieve.sh
  sh /Oya/uart/uart_process.sh
}

stop() {
  processpid=`uart pid process get`
  recievepid=`uart pid recieve get`
  kill -9 ${processpid}
  kill -9 ${recievepid}
  uart pid process remove
  uart pid recieve remove
}

boot() {
	/etc/init.d/uart enable
}
