#!/bin/sh /etc/rc.common

START=99
STOP=99

# Uploading starts only when the device is linked to the user on the backend (defaulted to true on this version of the firmware) and connected to the internet

start() {
  islinked=`state islinked get`
  internet_status=`internet_status connected get`
  if [ ${internet_status} == "1" ]; then
    if [ ${islinked} == "1" ]; then
      if [ ! -f /Oya/pid/uploading ]; then
        sh /Oya/uploading.sh
        state uploading set 1
      fi
    fi
  fi
}

stop() {
  uploadPid=`uploading pid get`
  kill -9 ${uploadPid}
  uploading pid remove
  state uploading set 0
}

boot() {
	/etc/init.d/uploading enable
  /etc/init.d/uploading start
}
